########################### Default configuration ######################
baseURL = "https://dev-stephanie-lacassagne.netlify.app"
title = ""
onglet = "Stéphanie Lacassagne"
theme = "bexar-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "bexer" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # desable language from here

[outputs]
home = ["HTML", "RSS", "JSON"]
  
############################### Plugins #################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

########################### navigation ################################
# main menu
[[menu.main]]
name = "La sexologie"
URL = "sexologie"
weight = 2

[[menu.main]]
name = "La psychologie énergétique "
URL = "psychologie-energetique"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 7

# footer menu
[[menu.footer]]
name = "Mentions légales"
URL = "terms"
weight = 1

[[menu.footer]]
name = "Politique de confidentialité"
URL = "privacy-policy"
weight = 2

########################### Default parameters ######################
[params]
logo = "images/Stephanie-Lacassagne-Favicon.png"
logo_footer = "images/Stephanie-Lacassagne-Favicon.png"
# top header
top_header = false
# Meta data
description = "This is meta description"
author = "WebPlusUn"
# contact info
address = "association Ekitegia, 33 chemin de l’aquitaine 64100 Bayonne"
mobile = "0788319163"
email = "sexobayonne@protonmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# page sidebar quick contact form
quick_contact = false
# search
search = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = false
label = "get a quote"
link = "contact"

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "43.4864323"
map_longitude = "-1.4676417,17"
map_marker = "images/marker.png"

########################### social icon ############################
[[params.social]]
icon = "fa-facebook"
URL = "https://facebook.com/themefisher"

[[params.social]]
icon = "fa-twitter"
URL = "https://twitter.com/themefisher"

[[params.social]]
icon = "fa-github"
URL = "https://github.com/themefisher"

[[params.social]]
icon = "fa-instagram"
URL = "https://instagram.com/themefisher"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = ""
# copyright
copyright = "&copy; [WebPlusUn](https://webplusun.fr) - [MaBulleDesign](mailto:beigbiza@gmail.com) tous droits réservés"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# footer content
footer_content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit. Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"